FROM rockylinux/rockylinux:10
RUN dnf install -y --allowerasing \
    bash coreutils findutils diffutils procps-ng \
    perl file ed hostname util-linux \
    wget curl ca-certificates gawk sed grep tar gzip \
    && (dnf install -y inotify-tools || true) \
    && (dnf install -y --enablerepo=crb yara || true) \
    && dnf clean all

# Install BATS + helpers
RUN mkdir -p /opt/bats && \
    wget -qO- https://github.com/bats-core/bats-core/archive/refs/tags/v1.11.0.tar.gz | \
      tar xz -C /opt/bats --strip-components=1 && \
    /opt/bats/install.sh /usr/local && \
    mkdir -p /usr/local/lib/bats/bats-support && \
    wget -qO- https://github.com/bats-core/bats-support/archive/refs/tags/v0.3.0.tar.gz | \
      tar xz -C /usr/local/lib/bats/bats-support --strip-components=1 && \
    mkdir -p /usr/local/lib/bats/bats-assert && \
    wget -qO- https://github.com/bats-core/bats-assert/archive/refs/tags/v2.1.0.tar.gz | \
      tar xz -C /usr/local/lib/bats/bats-assert --strip-components=1

COPY . /opt/lmd-src
COPY tests/ /opt/tests/

# Ensure cron directories exist for watchdog install
RUN mkdir -p /etc/cron.weekly

RUN cd /opt/lmd-src && ./install.sh && \
    sed -i 's/^autoupdate_signatures=.*/autoupdate_signatures="0"/' /usr/local/maldetect/conf.maldet && \
    sed -i 's/^autoupdate_version=.*/autoupdate_version="0"/' /usr/local/maldetect/conf.maldet && \
    sed -i 's/^autoupdate_version_hashed=.*/autoupdate_version_hashed="0"/' /usr/local/maldetect/conf.maldet && \
    sed -i 's/^email_alert=.*/email_alert="0"/' /usr/local/maldetect/conf.maldet && \
    sed -i 's/^scan_clamscan=.*/scan_clamscan="0"/' /usr/local/maldetect/conf.maldet && \
    sed -i 's/^import_config_url=.*/import_config_url=""/' /usr/local/maldetect/conf.maldet && \
    sed -i 's/^scan_ignore_root=.*/scan_ignore_root="0"/' /usr/local/maldetect/conf.maldet && \
    sed -i 's/^scan_tmpdir_paths=.*/scan_tmpdir_paths=""/' /usr/local/maldetect/conf.maldet

RUN cp /usr/local/maldetect/conf.maldet /usr/local/maldetect/conf.maldet.clean && \
    cp -a /usr/local/maldetect/sigs /usr/local/maldetect/sigs.clean

WORKDIR /opt/tests
CMD ["bats", "--formatter", "tap", "/opt/tests/"]
