HOST:      {{HOSTNAME}}
SCAN ID:   {{SCAN_ID}}
STARTED:   {{SCAN_STARTED}}
MODE:      inotify digest
ELAPSED:   {{MONITOR_RUNTIME}}

PATH:          {{SCAN_PATH}}
RANGE:         {{SCAN_RANGE}}
TOTAL FILES:   {{TOTAL_FILES}}
TOTAL HITS:    {{TOTAL_HITS}}
TOTAL CLEANED: {{TOTAL_CLEANED}}

{{QUARANTINE_WARNING_TEXT}}
{{CLEANED_SECTION_TEXT}}
{{SUSPENDED_SECTION_TEXT}}
{{HOOK_SECTION_TEXT}}
FILE HIT LIST:
