# maldet RPM spec — generated by pkg_gen.sh from pkg_lib templates
#
# Placeholders (substituted by pkg_gen.sh from project manifest):
#   maldet             — package name (e.g., bfd, apf, maldet)
#   2.0.1          — version string (e.g., 2.0.1)
#   Linux Malware Detect — malware scanner for Linux          — one-line package summary
#   Linux Malware Detect (LMD) is a malware scanner for Linux designed around the threats faced in shared hosted environments. It uses threat data from network edge intrusion detection systems to extract malware that is actively being used in attacks and generates signatures for detection. Features include MD5 hash, HEX pattern, statistical analysis, and YARA rule scanning, inotify real-time monitoring, ClamAV integration, quarantine/restore/clean operations, and multi-channel alerting (email, Slack, Telegram, Discord).      — multi-line package description
#   GPLv2+           — license identifier (e.g., GPLv2+)
#   https://github.com/rfxn/linux-malware-detect              — upstream URL
#   R-fx Networks <proj@rfxn.com>       — maintainer name + email
#   /usr/local/maldetect     — legacy install path (e.g., /usr/local/bfd)
#   maldet         — binary name in /usr/sbin
#   /usr/local/sbin/maldet       — legacy binary path (e.g., /usr/local/sbin/bfd)
#   1          — man page section (e.g., 1, 8)
#   2002  — copyright start year (e.g., 1999, 2002)
#   @@PKG_RPM_REQUIRES@@     — Requires: lines (one per line)
#   @@PKG_RPM_WEAK_DEPS@@    — Recommends/Suggests lines (conditional on el8+)
#   @@PKG_RPM_BUILD_SECTION@@     — %build section commands
#   @@PKG_RPM_INSTALL_SECTION@@   — %install section commands
#   @@PKG_RPM_PRE_SECTION@@       — %pre scriptlet body
#   @@PKG_RPM_POST_SECTION@@      — %post scriptlet body
#   @@PKG_RPM_PREUN_SECTION@@     — %preun scriptlet body
#   @@PKG_RPM_POSTUN_SECTION@@    — %postun scriptlet body
#   @@PKG_RPM_FILES_SECTION@@     — %files listing
#   @@PKG_RPM_CHANGELOG@@         — %changelog entries
#
%define name    maldet
%define version 2.0.1
%define release 1%{?dist}

# Legacy install path used by install.sh — symlink farm target
%define legacy_path /usr/local/maldetect

Name:           %{name}
Version:        %{version}
Release:        %{release}
Summary:        Linux Malware Detect — malware scanner for Linux
License:        GPLv2+
URL:            https://github.com/rfxn/linux-malware-detect
Source0:        %{name}-%{version}.tar.gz
BuildArch:      noarch

@@PKG_RPM_REQUIRES@@
@@PKG_RPM_WEAK_DEPS@@

%description
Linux Malware Detect (LMD) is a malware scanner for Linux designed around the threats faced in shared hosted environments. It uses threat data from network edge intrusion detection systems to extract malware that is actively being used in attacks and generates signatures for detection. Features include MD5 hash, HEX pattern, statistical analysis, and YARA rule scanning, inotify real-time monitoring, ClamAV integration, quarantine/restore/clean operations, and multi-channel alerting (email, Slack, Telegram, Discord).

%prep
%setup -q -n %{name}-%{version}

%build
@@PKG_RPM_BUILD_SECTION@@

%install
rm -rf %{buildroot}
@@PKG_RPM_INSTALL_SECTION@@

%pre
@@PKG_RPM_PRE_SECTION@@

%post
@@PKG_RPM_POST_SECTION@@

%preun
@@PKG_RPM_PREUN_SECTION@@

%postun
@@PKG_RPM_POSTUN_SECTION@@

%files
%license COPYING.GPL
@@PKG_RPM_FILES_SECTION@@

%changelog
@@PKG_RPM_CHANGELOG@@
